### ISSUE TITLE
transform_node assumes Pod::Elemental::Node (or a duck-type like it) input

### ISSUE THREAD

**Issue by jscook** [jscook/Pod-Elemental-Transformer-List#1]
transform_node does not check the $node parameter for a type. This could be done with Safe::Isa or another method. Passing in something which doesn't provide a 'children' method causes a undefined error.

We could put a check in either:

- Pod::Elemental::Transformer::List::transform_node

- Pod::Elemental::Transformer with a moose modifier (before) on transform_node

**Comment by rjbs** [comment]
I guess between the two I'd prefer the second, but I'm not sure it's really needed.

**Comment by jscook** [comment]
i can implement it as a test instead
