### ISSUE TITLE
run perlcritic with rjbs perlcriticrc

### ISSUE THREAD

**Issue by jscook** [jscook/Pod-Elemental-Transformer-List#5]
Perhaps this would help eliminate code or clean things up.

**Comment by jscook** [comment]
Initial look:

Policy "Perl::Critic::Policy::Bangs::ProhibitCommentedOutCode" is not installed.
Policy "Perl::Critic::Policy::Bangs::ProhibitFlagComments" is not installed.
Policy "Perl::Critic::Policy::Miscellanea::RequireRcsKeywords" is not installed.
No package-scoped "$VERSION" variable found at line 1, column 1.  See page 404 of PBP.  (Severity: 2)
Link L<Pod::Elemental::Document> on line 10 does not specify text at line 8, column 1.  Without text, you are at the mercy of the POD translator.  (Severity: 2)
Missing "NAME" section in POD at line 8, column 1.  See pages 133,138 of PBP.  (Severity: 2)
Missing "AUTHOR" section in POD at line 8, column 1.  See pages 133,138 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 288, column 3.  See page 53 of PBP.  (Severity: 2)
Quotes used with a noisy string at line 289, column 3.  See page 53 of PBP.  (Severity: 2)
4 is not one of the allowed literal values (0, 1, 2). Use the Readonly or Const::Fast module or the "constant" pragma instead at line 355, column 21.  Unnamed numeric literals make code less maintainable.  (Severity: 2)
Capture variable used outside conditional at line 356, column 18.  See page 253 of PBP.  (Severity: 3)
Private subroutine/method '__paras_for_num_marker' declared but not used at line 370, column 1.  Eliminate dead code.  (Severity: 3)
Private subroutine/method '__paras_for_def_marker' declared but not used at line 382, column 1.  Eliminate dead code.  (Severity: 3)
Private subroutine/method '__paras_for_bul_marker' declared but not used at line 394, column 1.  Eliminate dead code.  (Severity: 3)
Quotes used with a noisy string at line 400, column 18.  See page 53 of PBP.  (Severity: 2)

**Comment by rjbs** [comment]
This would probably have to get run (a)  against the built version of the code, not the git repo.  Dist::Zilla would fix a number of these things.  I think there's a plugin for Perl::Critic testing. I bet it's called Test::PerlCritic.

That said, I hardly use P::C anymore.  I find it to be more trouble than it's worth.
